use crate::symbol::{Rs, Rd, IW, IL, K, F, Address, FS, FE, N, Offset8, Offset16, Z, Condition};

#[derive(Debug, Clone, Copy)]
pub enum Instruction {
    // Arithmetic/Logical/Comparison
    Abs(Rd),
    Add(Rs, Rd),
    Addc(Rs, Rd),
    Addiw(IW, Rd),
    Addil(IL, Rd),
    Addk(K, Rd),
    Addxy(Rs, Rd),
    And(Rs, Rd),
    Andi(IL, Rd),
    Andn(Rs, Rd),
    Andni(IL, Rd),
    Btstk(K, Rd),
    Btst(Rs, Rd),
    Clr(Rd),
    Clrc,
    Cmp(Rs, Rd),
    Cmpiw(IW, Rd),
    Cmpil(IL, Rd),
    Cmpxy(Rs, Rd),
    Dec(Rd),      
    Divs(Rs, Rd),
    Divu(Rs, Rd),
    Lmo(Rs, Rd),
    Mods(Rs, Rd),
    Modu(Rs, Rd),
    Mpys(Rs, Rd),
    Mpyu(Rs, Rd),
    Neg(Rd),
    Negb(Rd),
    Not(Rd),
    Or(Rs, Rd),
    Ori(IL, Rd),
    Setc,
    Sext(Rd, F),
    Sub(Rs, Rd),
    Subb(Rs, Rd),
    Subiw(IW, Rd),
    Subil(IL, Rd),
    Subk(K, Rd),
    Subxy(Rs, Rd),
    Xor(Rs, Rd),
    Xori(IL, Rd),
    Zext(Rd, F),
    // Move
    MovbRegToIndirect(Rs, Rd),
    MovbIndirectToReg(Rs, Rd),
    MovbIndirectToIndirect(Rs, Rd),
    MovbRegToIndirectOffset(Rs, Rd, Offset8),
    MovbIndirectToRegOffset(Rs, Rd, Offset8),
    MovbIndirectToIndirectOffset(Rs, Rd, Offset8),
    MovbRegToAbsolute(Rs, Address),
    MovbAbsoluteToReg(Address, Rd),
    MovbAbsoluteToAbsolute(Address, Address),
    MoveReg(Rs, Rd),
    MoveFieldRegToIndirect(Rs, Rd, Option<F>),
    MoveFieldRegToIndirectPredec(Rs, Rd, Option<F>),
    MoveFieldRegToIndirectPostinc(Rs, Rd, Option<F>),
    MoveFieldIndirectToReg(Rs, Rd, Option<F>),
    MoveFieldIndirectPredecToReg(Rs, Rd, Option<F>),
    MoveFieldIndirectPostincToReg(Rs, Rd, Option<F>),
    MoveFieldIndirectToIndirect(Rs, Rd, Option<F>),
    MoveFieldIndirectToIndirectPredec(Rs, Rd, Option<F>),
    MoveFieldIndirectToIndirectPostinc(Rs, Rd, Option<F>),
    MoveFieldRegToIndirectOffset(Rs, Rd, Option<F>, Offset8),
    MoveFieldIndirectToRegOffset(Rs, Rd, Option<F>, Offset8),
    MoveFieldIndirectToIndirectOffsetPostinc(Rs, Rd, Option<F>, Offset8),
    MoveFieldIndirectToIndirectOffset(Rs, Rd, Option<F>, Offset8, Offset8),
    MoveFieldRegToAbsolute(Rs, Address, Option<F>),
    MoveFieldAbsoluteToReg(Address, Rd, Option<F>),
    MoveFieldAbsoluteToIndirectPostinc(Address, Rd, Option<F>),
    MoveFieldAbsoluteToAbsolute(Address, Address, Option<F>),
    Moviw(IW, Rd),
    Movil(IL, Rd),
    Movk(K, Rd),
    Movx(Rs, Rd),
    Movy(Rs, Rd),
    // Graphics
    Cpw(Rs, Rd),
    Cvxyl(Rs, Rd),
    Drav(Rs, Rd),
    Filll,
    Fillxy,
    Line(Z),
    Pixbltbl,
    Pixbltbxy,
    Pixbltll,
    Pixbltxyl,
    Pixbltxyxy,
    PixtRegToIndirect(Rs, Rd),
    PixtRegToIndirectxy(Rs, Rd),
    PixtIndirectToReg(Rs, Rd),
    PixtIndirectToIndirect(Rs, Rd),
    PixtIndirectxyToReg(Rs, Rd),
    PixtIndirectxytoIndirectxy(Rs, Rd),
    // Control
    Call(Rs),
    Calla(Address),
    Callr(Offset16),
    Dint,
    Eint,
    Emu,
    Exgf(Rd, F),
    Exgpc(Rd),
    Getpc(Rd),
    Getst(Rd),
    Nop,
    Popst,
    Pushst,
    Putst(Rs),
    Reti,
    Rets(N),
    Rev(Rd),
    Setf(FS, FE, F),
    Trap(N),
    // Jump
    Dsj(Rd, Offset16),
    Dsjeq(Rd, Offset16),
    Dsjne(Rd, Offset16),
    Dsjs(Rd, Offset16),
    Ja(Condition, Offset16),
    Jr(Condition, Offset16),
    Jrs(Condition, Offset16),
    Jump(Rs),
    // Shift
    Rlk(K, Rd),
    Rl(Rs, Rd),
    Slak(K, Rd),
    Sla(Rs, Rd),
    Sllk(K, Rd),
    Sll(Rs, Rd),
    Srak(K, Rd),
    Sra(Rs, Rd),
    Srlk(K, Rd),
    Srl(Rs, Rd),
}
